apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hvtf8wjp5-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:2611903df679e6fe3f7d946311e603eea1aba9a3@sha256:f4d240fc90db28c6ed3698ab23b37a9d42d161e417fe27d5ed6c1d000a73c668
          name: container-image
