apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hvtf8wjp5-python
  janus-idp.io/tekton: hvtf8wjp5-python
  backstage.io/kubernetes-id: hvtf8wjp5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hvtf8wjp5-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
